[package]
name = "sr-api-macros"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[lib]
proc-macro = true

[dependencies]
quote = "0.6"
syn = { version = "0.15", features = [ "full", "fold", "extra-traits" ] }
proc-macro2 = "0.4"
